<a href="https://colab.research.google.com/github/69909/netflix-clone-project-by-Anmol-surolia/blob/main/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [6]:
iris_test= pd.read_excel("/content/1750577561477-iris-test.xlsx")

In [7]:
iris_test

    sepallength  sepalwidth  petallength  petalwidth            class
0           5.4         3.0          4.5         1.5  Iris-versicolor
1           5.3         3.7          1.5         0.2      Iris-setosa
2           5.2         4.1          1.5         0.1      Iris-setosa
3           5.2         3.5          1.5         0.2      Iris-setosa
4           5.2         3.4          1.4         0.2      Iris-setosa
5           5.2         2.7          3.9         1.4  Iris-versicolor
6           5.1         3.8          1.9         0.4      Iris-setosa
7           5.1         3.8          1.6         0.2      Iris-setosa
8           5.1         3.8          1.5         0.3      Iris-setosa
9           5.1         3.7          1.5         0.4      Iris-setosa
10          5.1         3.5          1.4         0.2      Iris-setosa
11          5.1         3.5          1.4         0.3      Iris-setosa
12          5.1         3.4          1.5         0.2      Iris-setosa
13          5.1         3.3          1.7         0.5      Iris-setosa
14          5.1         2.5          3.0         1.1  Iris-versicolor
15          5.0         3.6          1.4         0.2      Iris-setosa
16          5.0         3.5          1.6         0.6      Iris-setosa
17          5.0         3.5          1.3         0.3      Iris-setosa
18          5.0         3.4          1.6         0.4      Iris-setosa
19          5.0         3.4          1.5         0.2      Iris-setosa
20          5.0         3.3          1.4         0.2      Iris-setosa
21          5.0         3.2          1.2         0.2      Iris-setosa
22          5.0         3.0          1.6         0.2      Iris-setosa
23          5.0         2.3          3.3         1.0  Iris-versicolor
24          5.0         2.0          3.5         1.0  Iris-versicolor
25          4.9         3.1          1.5         0.1      Iris-setosa
26          4.9         3.1          1.5         0.1      Iris-setosa
27          4.9         3.1          1.5         0.1      Iris-setosa
28          4.9         3.0          1.4         0.2      Iris-setosa
29          4.9         2.5          4.5         1.7   Iris-virginica
30          4.9         2.4          3.3         1.0  Iris-versicolor
31          4.8         3.4          1.9         0.2      Iris-setosa
32          4.8         3.4          1.6         0.2      Iris-setosa
33          4.8         3.1          1.6         0.2      Iris-setosa

In [10]:
iris_train= pd.read_excel("/content/1750577562424-iris-train.xlsx")
iris_train

     sepallength  sepalwidth  petallength  petalwidth           class
0            7.9         3.8          6.4         2.0  Iris-virginica
1            7.7         3.8          6.7         2.2  Iris-virginica
2            7.7         3.0          6.1         2.3  Iris-virginica
3            7.7         2.8          6.7         2.0  Iris-virginica
4            7.7         2.6          6.9         2.3  Iris-virginica
..           ...         ...          ...         ...             ...
111          4.5         2.3          1.3         0.3     Iris-setosa
112          4.4         3.2          1.3         0.2     Iris-setosa
113          4.4         3.0          1.3         0.2     Iris-setosa
114          4.4         2.9          1.4         0.2     Iris-setosa
115          4.3         3.0          1.1         0.1     Iris-setosa

[116 rows x 5 columns]

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [14]:
model = RandomForestClassifier()
X= iris_train.iloc[:, :-1]
y= iris_train.iloc[:,-1]
display(X)
display(y)
model.fit(X,y)
prediction = model.predict(X)
prediction

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

array(['Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [15]:
iris_test
X= iris_test.iloc[:, :-1]
y= iris_test.iloc[:, -1]
model= DecisionTreeClassifier()
model.fit(X,y)
prediction = model.predict([[7.7,2.6,6.9,2.3]])
prediction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-virginica'], dtype=object)